### ISSUE TITLE
Expose certain (or all) compiler switches

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1013]
**Is your feature request related to a problem? Please describe.**
One of the great features of VB6 is hackability. Standard DLLs were created in part with the undocumented [VBCompiler] field in .vbp files adding /ENTRY:DllMain. While TB now allows creating those in a more friendly manner, there's other uses for compiler switches. 

**Describe the solution you'd like**
Primarily, I'd like the /ENTRY, /SUBSYSTEM and /FIXED:NO switches exposed, if not just all of them via a textbox. Since TB doesn't have a runtime and compiles to native code, Wayne suggests it could, like VB6 (though with much more difficulty since you need to strip the runtime out), be used to create kernel mode drivers, if we could add the /ENTRY:DriverEntry /SUBSYSTEM:NATIVE /FIXED:NO switches.

**Describe alternatives you've considered**
I do not believe any alternative to modify the compiled exe exists.

**Additional context**
Me and Wayne discussed this on VBForums; thought I'd add a formal feature request for tracking purposes like the other issues.

**Comment by WaynePhillipsEA** [comment]
In BETA 82, there is now a project setting for `Project: Native Subsystem`.  On it's own this is not particularly useful, as we also need to be able to override the entry point before being able to create kernel mode drivers.   ps. At the moment, all tB DLL builds have relocation data, so /FIXED:NO is implicit.

**Comment by wqweto** [comment]
Building low-level device drivers with TB would be a nice feature for marketing.

**Comment by fafalone** [comment]
Indeed. It's something that's outright impossible in managed languages like .NET.

Plus one of the things that's made me such a big fan of VB6 is how it allows you to use high level language features to get things done at that level, but allows you to drop down into lower levels as needed... which .NET throws up big roadblocks to.

While it's somewhat of a novelty, it speaks to that power. And just imagine the waves at Microsoft the first time someone sends them a driver for signing written in a direct successor to VB6 with full backwards compatibility. Maybe think about built in support for inline C/ASM too. 

I'm determined to make a drive controller driver. I want to intercept requests at the low level needed to block everything, because Windows itself has incurred my wrath by spinning up idle drives for no damn good reason. Kernel event tracing is the only method that revealed exactly what was causing it at all.

**Comment by mansellan** [comment]
Heh, I'm on record as being a big C# fan. But I would be overjoyed if twinBASIC could do something that C' can't.

**Comment by fafalone** [comment]
It already does. Can't make a standard DLL with C# without a wrapper done in another language.

**Comment by WaynePhillipsEA** [comment]
With BETA 83, we have some new project settings:  `Override Entry Point` for overriding the DLL entry point, and `Runtime Binding Of DLL Declares (ADVANCED)` to allow binding DLL declares through the IAT (default `Yes`, you must set this to `No`).

Note that if you're trying to build a kernel mode driver, you'll need to use `[ UseGetLastError (False) ]` before any Declares in order to ensure the tB compiler doesn't issue calls to `GetLastError` implicitly.   Obviously there are a lot of implicit system DLL calls used by the compiler for handling of Strings / Variants / Arrays etc, so none of those will work in kernel mode.  If you accidentally try to use something that does make a system call, you'll see red errors in the build output telling you which incompatible DLL calls were issued (i.e. entry points outside of `ntoskrnl`).

In thoery, we should now be able to create a kernel-mode driver, though I haven't tested it yet.  I'm planning to try to port this RamDisk driver at some point: [ramdisk.c](http://joyasystems.com/sample-code%2FWindows%20Driver%20Samples%2FRAMDisk%20Storage%20Driver%20Sample%2FC%2B%2B%2Fsrc%2Framdisk.c)

**Comment by mansellan** [comment]
Just wondering if it's worth having a project-level setting to set the default `UseGetLastError` behaviour, rather than having to decorate every Declare?

**Comment by wqweto** [comment]
Just a mental note that it is not in the spirit of BASIC what you've done here! How dare you! :-))

**Comment by fafalone** [comment]
But it's in the spirit of Visual Basic, which The trick showed us how to hack to produce kernel mode drivers like this :)

The quickest test would be [TrickMemReader](https://www.vbforums.com/showthread.php?788179-VB6-Kernel-mode-driver), the VB6 driver demo, as it's already in VB. 

Or a simple 'hello world' driver like the one in Geoff Chappell's very promising [article on loading self-signed kernel mode drivers](https://www.geoffchappell.com/notes/windows/license/customkernelsigners.htm) under Win10 x64+SecureBoot.

**Comment by fafalone** [comment]
The entry redirect is not working...

[COMPILER] error binding to procedure DriverEntry(): too few arguments, expected 2 in call to 'DriverEntry'

but it has 2 arguments

Public Function DriverEntry(DriverObject As DRIVER_OBJECT, RegistryPath As UNICODE_STRING) As Long

**Comment by WaynePhillipsEA** [comment]
> The entry redirect is not working...

Should be fixed in BETA 84, thanks!

**Comment by fafalone** [comment]
The compiler is still seeing the imports from the original entry point
WARNING: USE OF INVALID DLLs IN KERNEL MODE...
    KERNEL32.dll!GetProcessHeap
    KERNEL32.dll!HeapAlloc
    OLEAUT32.dll!#150
    OLEAUT32.dll!#200
etc

It says warning but it's not building.

**Comment by WaynePhillipsEA** [comment]
@fafalone could you send me the twinproj file so far, and I'll take a look at that tomorrow morning.  Thanks

**Comment by fafalone** [comment]
Sure, it's not meant to run at this point, just to test compiling and look at the .sys for depends.

It also doesn't recognize ntoskrnl.exe... ntoskrnl.exe!DbgPrint is listed among the 'invalid in kernel mode' dlls.

[DllDependTest.zip](https://github.com/twinbasic/twinbasic/files/9184814/DllDependTest.zip)

**Comment by WaynePhillipsEA** [comment]
Yeah, it would need just `ntoskrnl` at the moment.  I'll get that fixed when I sorry this tomorrow.  Thanks

**Comment by WaynePhillipsEA** [comment]
This is fixed in the next release.  However, note that at the moment the ParamArray in DbgPrint cannot be used in kernel mode because internally the compiler uses a SAFEARRAY as temporary storage for the arguments.

**Comment by WaynePhillipsEA** [comment]
BETA 85 fixes the crash you were encountering, and a few other minor bits.

**Comment by fafalone** [comment]
Just had time for a quick check right now, looking good... successfully builds dependency free binary.

A couple minor things, [ UseGetLastError (False) ] is required; otherwise it still imports the GetLastErrorAPI... should probably default to false when native subsystem flag is enabled.

${FileExtension} should default to .sys when native flag enabled.

**Comment by WaynePhillipsEA** [comment]
BETA 86 now defaults UseGetLastError to false when `Native Subsystem` is set, and `${FileExtension}` to `sys`.  Thanks

**Comment by fafalone** [comment]
The /DRIVER flag should be exposed as well; WDM drivers would need /DRIVER:WDM. Also wondering, have been using a standard dll project type for this since that has the /FIXED:NO already in effect; but does it specify any DLL-related switches (/DLL, /LIBRARY) that would interfere with a driver? If so, they should be switch off if /SUBSYSTEM:NATIVE is in effect.

I'm finishing up writing a dead simple 'hello world' driver demo, hope to test this week.

**Comment by fafalone** [comment]
In Beta 86, the extension *is not* changed to .sys when the the native subsystem option is enabled.

[LINKER] SUCCESS created output file 'C:\tbproj\HelloWorldDriver\Build\NewProject_win32.dll'

**Comment by fafalone** [comment]
Also, I got an absolute flood of dependencies when there should have been any.

**Comment by fafalone** [comment]
Nevermind, runtime declare setting got flipped somehow.
