### ISSUE TITLE
KeyDown no action in picturebox

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#1356]
Do nothing

Class Form1
    Private Sub Picture1_KeyDown(KeyCode As Integer, Shift As Integer)
        If KeyCode = 40 Then                ' vers le bas
            MsgBox KeyCode
        ElseIf KeyCode = 38 Then           ' vers le haut
            MsgBox KeyCode
        ElseIf KeyCode = 39 Then         ' vers la droite
            MsgBox KeyCode
        ElseIf KeyCode = 37 Then         ' vers la gauche
            MsgBox KeyCode
        End If
    End Sub
End Class

 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 175

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 176, thanks!

**Comment by camomille22003** [comment]
I see that the arrow keys are now recognized, but in reality there were 2 problems because since the "setfocus" is still not implemented in the PictureBox, I have to simulate a click on it to give it focus before using the keys.

**Comment by WaynePhillipsEA** [comment]
PictureBox.SetFocus now implemented in BETA 177, thanks.

**Comment by camomille22003** [comment]
Sorry, but the focus still hasn't passed to the PictureBox.
I made an example in Vbx and Tb.
The movement is done with the down arrow key and the focus should change from the "OptionButton" to the movement of my cursor.
We also distinguish on the Tb version that the cursor (black) cannot pass over .Line()-(),,BF (yellow) #1354
Vbx :
![Vb6Setfocus](https://user-images.githubusercontent.com/33807881/201921934-e881336c-43d5-49d7-83d7-5912c7a2deff.gif)
Tb :
![Tb6Setfocus](https://user-images.githubusercontent.com/33807881/201922056-d9533b64-a8a9-4067-98be-6581e337e89b.gif)

[essai setfocus.zip](https://github.com/twinbasic/twinbasic/files/10012717/essai.setfocus.zip)
[Test setfocus.zip](https://github.com/twinbasic/twinbasic/files/10012718/Test.setfocus.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks... I will look at again.  Always best to provide a sample file to demonstrate when possible, so thanks for that.

**Comment by camomille22003** [comment]
problem fixed with 178 Thanks
