### ISSUE TITLE
v193 can't match event with handler

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1389]
v193 feels like another huge leap forwards. Thankyou.  Is it helpful to report bugs now or is there another release in progress?

I see lots of "unable to match this handler to its event member"
some of the events causing this are:
SStab_click
SStab_mousedown
SStab_mousemove
updown_mousemove
toolbar_mousedown
plus others

Also a gentle reminder that Zorder is still not implemented, my Problems pane is full of yellow warnings. :smile:

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [193]

**Comment by WaynePhillipsEA** [comment]
Interesting.   VB6 doesn't care if there is a mismatch of ByVal/ByRef specifiers for event handlers, so for example SSTab Click is actually defined in the type library as `Private Sub SSTab1_Click(ByVal PreviousTab As Integer)` but VBx allows, and defaults to `Private Sub SSTab1_Click(PreviousTab As Integer)`.   twinBASIC currently fails to match them up as it sees them as incompatible signatures.

**Comment by wqweto** [comment]
Btw, this is **not** allowed on (early-bound) classes in VB6 and bombs with
```
---------------------------
Microsoft Visual Basic
---------------------------
Compile error:

Procedure declaration does not match description of event or procedure having the same name
---------------------------
OK   Help   
---------------------------
```

Sample code:
```vba
'--- Class1
Option Explicit

Event Click(ByVal PreviousTab As Integer)
```
```vba
'--- Form1
Option Explicit

Private WithEvents m_oInstance As Class1

Private Sub m_oInstance_Click(PreviousTab As Integer) '<---- does not compile
    '
End Sub
```
For user-controls the IDE prepares some proxies/wrappers so all sited controls are actually called late-bound through these generated wrappers and some of their events are with changed signatures (pixels<->twips conversions) and new "extender" events are added in the process.

**Comment by WaynePhillipsEA** [comment]
Thanks @wqweto.   I have put a fix for this in the next release which only applies to dispinterface source interfaces, so that should match.   However, I will check this example you gave before release.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 194, thanks!

**Comment by dmrvb** [comment]
reOpened
This error is still present in v195 (I have not looked at v194)

**Comment by dmrvb** [comment]
errors also present in 194

**Comment by WaynePhillipsEA** [comment]
Hmm, certainly `SSTab_Click` looks fixed here...

Ah OK, `SSTab_MouseDown` / `SSTab_MouseMove` etc are still broken.  I'll get them fixed tomorrow.

**Comment by dmrvb** [comment]
Listbox Itemcheck  
ListView mousedown
updown  mousedown mouseup
toolbar mousedown
SStab mousedown mousemove mouseup
and just maybe a couple more.
I still struggle to navigate through a big list in the problems pane, up down keyboard keys don't work so doing it on the scrollbar which is not ideal but sort of ok with the mousewheel.

**Comment by WaynePhillipsEA** [comment]
These should be fixed in BETA 196.   Let me know if you find any that are still not correct.  Thanks

**Comment by dmrvb** [comment]
Listbox Itemcheck.
I will go through some other projects and look for any more but probably not till tomorrow.

**Comment by WaynePhillipsEA** [comment]
What ListBox are we talking about here?  The builtin one?

**Comment by dmrvb** [comment]
I think so,  or it could be a ListView. I will look now   and can't find any others

**Comment by dmrvb** [comment]
Yes, its the built in listbox.

**Comment by dmrvb** [comment]
I have a big real world outside project on today so no more software input till very late evening or tomorrow

**Comment by WaynePhillipsEA** [comment]
No problem, and thanks for the info

**Comment by dmrvb** [comment]
Issue still present in v197.
in VB6 the event is List1_ItemCheck(Item As Integer)
in tB its (item as long). 
This causes imported VB6 code to generate the error.
Changing to (Item as Long) fixes it.
I am happy to do this but to get full VB6 compatibility I assume it need sorting out?

**Comment by WaynePhillipsEA** [comment]
Yeah sorry I didn't get chance to look at that today.  Will fix tomorrow, cheers.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 198.  Thanks!
