### ISSUE TITLE
Parent of UserControl 

### ISSUE THREAD

**Issue by sphinxeg** [twinbasic/twinbasic#1532]
I have a UserControl which uses the Parent property but it fails and gives Unexpected error as shown in the screenshot

![UC_Parent](https://user-images.githubusercontent.com/7399157/228440688-d28a99c4-87ba-41de-ac6f-8c6587e6e54b.png)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 290, thanks!

**Comment by sphinxeg** [comment]
The problem still persists!

 
![ASR+Error](https://user-images.githubusercontent.com/7399157/230289421-398bc0c8-a59f-4450-837d-54d2ac29581d.jpg)

**Comment by WaynePhillipsEA** [comment]
Please provide a full example to demonstrate the problem.  The following example does not throw an error for me in BETA 290:

<img width="257" alt="tbUserControlParent1" src="https://user-images.githubusercontent.com/25738109/230319826-48ea7cfb-6e5b-441b-bb89-2c7748d23b01.png">

**Comment by sphinxeg** [comment]
![image](https://user-images.githubusercontent.com/7399157/230411582-e201de48-b96e-45e9-b63a-d93a2206c596.png)

**Comment by sphinxeg** [comment]
The IDE itself has a problem I think, I tried to remove 'Integer' and retype it again and it is small letter 'integer'

**Comment by WaynePhillipsEA** [comment]
Please provide the twinproj file for us to take a look.

**Comment by sphinxeg** [comment]
Could you please provide your email?

**Comment by WaynePhillipsEA** [comment]
Looking again at your screenshot, I can see that you're calling the code from the `InitProperties` event.  I can confirm that using the Parent object from the InitProperties (or ReadProperties) isn't yet supported in tB.  We can leave this issue open until fixed.

**Comment by sphinxeg** [comment]
> Looking again at your screenshot, I can see that you're calling the code from the `InitProperties` event. I can confirm that using the Parent object from the InitProperties (or ReadProperties) isn't yet supported in tB. We can leave this issue open until fixed.

Great, I can wait.
Good luck.

**Comment by fafalone** [comment]
```vba
        Private Sub UserControl_InitProperties() Handles UserControl.InitProperties
            Debug.Print "init props"
            Dim ct As Control
            For Each ct In UserControl.Parent
                Debug.Print ct.name
            Next
        End Sub
```
is working in 653 so considering this closed. Post a comment if there's still an issue.
