### ISSUE TITLE
tB not properly understanding VOID typelib aliases

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1688]
**Describe the bug**
Continued playing around with NeHe's OpenGL demos, on import of Lesson 12, encountered show-stopper errors:

vbogl.tlb:\
`Alias GLbyte As Byte`\
`Alias GLvoid As {void}`\
`Declare Sub glTexImage2D Lib "OPENGL32" (ByVal target As VBOpenGL.glTextureTargetConstants, ByVal level As VBOpenGL.GLint, ByVal internalFormat As VBOpenGL.GLint, ByVal width As VBOpenGL.GLsizei, ByVal height As VBOpenGL.GLsizei, ByVal border As VBOpenGL.GLint, ByVal format As VBOpenGL.glTIFormatConstants, ByVal Type As VBOpenGL.glPixelTypeConstants, ByVal pixels As VBOpenGL.GLvoid)`

OLEView decompile:
```
    typedef [public]
    void GLvoid;

GLvoid* pixels in glTextImage2D
```

i.e. just void*, shouldn't be a problem (and isn't in VB)

tB:
```
Dim TextureImage() As GLbyte
glTexImage2D glTexture2D, 0, 3, w, h, 0, GL_RGB, GL_UNSIGNED_BYTE, TextureImage(0, 0, 0)
```

{ERROR} /Lesson6/Sources/OGLUtils.bas [216,76]: Validation of call to 'glTexImage2D' failed.  Argument for 'pixels': cannot coerce type 'Byte' to '{void}'

**To Reproduce**
Project attached.

**Expected behavior**
Correctly process this scenario as VB6 does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.398
 
**Additional context**
Some identifiers in this post and project reference lesson06 or lesson02; this are all as they are in the original lesson12 files, nothing has been mixed.

[lesson12.zip](https://github.com/twinbasic/twinbasic/files/12773992/lesson12.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 441.  Thanks.

**Comment by fafalone** [comment]
This issue seems to not have ever been completely fixed; lesson12 is broken in VB6 too but lesson14 and others are still crashing on void* alias calls.

[lesson14.zip](https://github.com/twinbasic/twinbasic/files/15254286/lesson14.zip)
