### ISSUE TITLE
Controls not visible or vanish

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1980]
**Describe the bug**
Big multi form project. Many controls are not visible when app runs but do become visible on a mousemove over the control, or in some cases a click is required. Some controls vanish when user clicks/activates another form.

**To Reproduce**
Pre-anouncement of bug, does not yet reproduce in simple test progs.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [626]

**Additional context**
This is a new issue in recent releases
bad in 624 onwards   was ok in 615, (looks like I have missed a few releases.)

**Comment by azianwolfpunk** [comment]
I am also experiencing this vanishing controls on Beta 637, last working for me was Beta 622.

**Comment by dmrvb** [comment]
I still can't create a simple test prog. to replicate this.
I see a lot of GUI related "Wayne" messages in the debug.console, I don't know if these relate to the bug.

**Comment by dmrvb** [comment]
In my large app it appears that CLS is removing all controls whilst it should only clear graphics generated at run time.
Controls become visible again on mousemove over control.
Currently can not replicate in simple test prog.

**Comment by AlanSkyNet** [comment]
If you are adding controls to a form, all is well until you save the form.
When you open the form the show method hides portions of the form.
All was working in beta 622.

**Comment by dmrvb** [comment]
I see this issue in 2 of my 3 big projects but I can't make it happen in any smaller test programs. Are you able to make it happen in a small test project that you could send to Wayne???

**Comment by dmrvb** [comment]
**This is still a major issue for me.**
Here is a test program derived by reducing a big project to a single form with almost all code removed.
It also gives a second bug (No such interface supported "red box").

When red box shows please click resume next.
(This red box bug needs fixing but I don't think it directly relates to the missing controls bug.)

A form will now display with most controls missing.
Moving the mouse over the missing controls will make some visible.
Selecting a tab will show the controls
Resizing the form will show the controls.
Clicking the help help menu will do a CLS which will make the controls vanish again.

I don't think that CLS is the only source of this bug.
I don't think that the Tab control is an essential factor.

Let me know if there is anything else that I can do to help.

.txt added to filename as twinproj not allowed

[Missing Controls1.twinproj.txt](https://github.com/user-attachments/files/18623864/Missing.Controls1.twinproj.txt)

**Comment by JimDrewGH** [comment]
I tried your project - it's missing an Active-X, but if you click through the Resume/Next a few times it launches and I also see what you are talking about with the forms missing boxes and such until you move the mouse over and/or start clicking around the form.  So, you're not crazy and the issue is not related to your particular setup.

**Comment by dmrvb** [comment]
Thanks Wayne.
Which ActiveX is missing? They should all be standard VB controls.
I don't get the "red box" on my full project, it only appeared when I reduce the project, so I don't understand whats missing.
Anyway, if you can fix this then it might be the last big hurdle to getting my three big projects running in tB.
There are a few (hopefully) minor issues at run time but it feels like its all getting very close now. Well done.

**Comment by JimDrewGH** [comment]
I'm not Wayne... just a supporter of tB.  :)  I have seen some oddities with forms and so I wanted to see if I also have the same issue with your application, and I do.

I ran the app again and now I only get a single error in the "ActiveXExtenerX.twin" file... which is something that tB is adding to the project.

Here is the error I see:

![Image](https://github.com/user-attachments/assets/d7fe0ba9-2fed-4643-8635-24936e98bcb2)

Made a screen capture video, but it is too large to post here.  I can see if it can be posted on the Discord.

**Comment by JimDrewGH** [comment]
I posted the video in the Discord and received a comment that this issue was corrected with beta 671.  I am about to test that.

**Comment by dmrvb** [comment]
I believe that I am running tB671 though it incorrectly declares itself as 670????

**Comment by dmrvb** [comment]
I can "fix" the "red box" by removing some controls but the vanishing controls issue remains.
I think the red box might relate to a control array of slider controls. I will pin this down later today. I think I have seen mention of this control array issue so Wayne is aware?.

**Comment by JimDrewGH** [comment]
I am not sure exactly what Wayne is aware of... there are a lot of issues being reported all of the time through here and the Discord.  The controls issue seems to be associated with whatever tB is installing itself (that is a .twin file that is generated).  The issue with the buttons and boxes not appearing is something completely different.

**Comment by dmrvb** [comment]
The red box is related to a toolbar, I will investigate more.

**The vanishing controls are due to a "caption = new name"  within the Form_Load** event. This somehow breaks the form so that the controls do not correctly draw themselves.

This is a bit hard to believe but its true, and I have had a couple of issues with setting the caption in VB6, maybe it does more than just setting the caption. 

This is not the whole story but should be enough for Wayne to sort it out????

**Comment by WaynePhillipsEA** [comment]
Thanks @dmrvb, it sounds like you've really narrowed down the issue, so it's time for me to take a look (tomorrow).

**Comment by WaynePhillipsEA** [comment]
Should be fixed in BETA 672.  Thanks for narrowing down the issue and providing an example project.
