### ISSUE TITLE
Intellisense prepends full function name to already typed chars

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#2037]
**Describe the bug**
This occurs when there's multiple matches and you use the arrow keys then Tab to select one other than the first.

If you have SomeFunction1, SomeFunction2, and SomeFunction3, then type Som and arrow down to 3, you wind up with SomeFunction3Som() with the cursor positioned after the 2nd S.

**To Reproduce**
```vba
    Private Function SomeFunction1() As Long
    
    End Function
    Private Function SomeFunction2() As Long
    
    End Function
    Private Function SomeFunction3() As Long
    
    End Function
    Sub test()
  
    End Sub
```
In `Sub test` type Som, use the arrow keys to select SomeFunction2 or SomeFunction3, then press Tab.

**Expected behavior**
Same correct behavior as space gives in this situation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version Beta 679
**Additional context**

**Comment by WaynePhillipsEA** [comment]
I can't seem to reproduce this.

**Comment by sokinkeso** [comment]
IIRC this issue fixed in BETA 672, it's not happening to me with latest BETAs.
The strange is that fafalone mentions it happens on 679...

**Comment by fafalone** [comment]
Still happening in 691.

![Image](https://github.com/user-attachments/assets/4fd5a7d7-6d9e-4da1-a53c-7b283f46d1d1)

**Comment by WaynePhillipsEA** [comment]
It doesn't repro here.   Have you got any keyboard customizations that are active! (that could be interfering somehow)

**Comment by WaynePhillipsEA** [comment]
Perhaps you copied the whole JSON for the built-in keyboard shortcuts group (from an earlier version of tB) into a custom group?  (which is not how it is supposed to be done, since there is built-in inheritence from the built in group)

**Comment by fafalone** [comment]
Hmm yes apparently that's exactly what I did... didn't know about inheritance.

Looking at the diff now, it appears at some point `"{KEYDOWN}TAB",` was added as the top entry to `"tbIntellisense_AcceptSelectedEntry"`, and my copy didn't have that; not a change I made, it was just to change make the switch between code/form designer into a toggle when someone asked about that.

A custom shortcut group with *only* that change,

```
{
	"tbIntellisense_AcceptSelectedEntry": [
		"SPACE",
		"ENTER",
		",",
		".",
		"+",
		"-",
		"&",
		"(",
		")",
		"!",
		"*",
		"\\",
		"/",
		":",
		"="
	]
}
```

reproduces the behavior. Not sure exactly why but yes seems to be an improper change on my part, apologies for the time wasted on this.
