### ISSUE TITLE
Label control flickering issue

### ISSUE THREAD

**Issue by dj-make** [twinbasic/twinbasic#2245]
Label control flickering issue

[NewProject.zip](https://github.com/user-attachments/files/22821751/NewProject.zip)

**Comment by dj-make** [comment]
> 标签控制闪烁问题
> 
> [NewProject.zip](https://github.com/user-attachments/files/22821751/NewProject.zip)

https://github.com/user-attachments/assets/b71302a3-7a4b-4bd7-bca3-b712d048a334

**Comment by wqweto** [comment]
JFYI, the ZIP above is a RAR file.

Confirmed the transparent label is **not** flickering in VB6 using the loop.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 892, thanks

**Comment by dj-make** [comment]
> 在 BETA 892 中修复，谢谢

When form.autoredraw is set to false, there is no flickering, but when set to true, flickering still occurs.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 893, thanks
