### ISSUE TITLE
LoadResData works in IDE but errors in compiled ActiveX DLL

### ISSUE THREAD

**Issue by TBDev111** [twinbasic/twinbasic#2280]
**Describe the bug**
LoadResData works in IDE but errors in compiled ActiveX DLL

**To Reproduce**

Create STRING Resource DefSilo.txt
Run:
strText = LoadResData("DefSilo.txt", "STRING")

This works fine in tB IDE.
Compile DLL and it generates Error:
-2147467259 Unspecified error.

**Expected behavior**
Work same as it does in the IDE.

**Screenshots**
NA

**Desktop (please complete the following information):**
OS: Windows 11
tB: 895

**Additional context**
This was tricky to debug as it is in a DLL.
Created a trace stack to find the error.
There are similar issues reported elsewhere with tB compiled EXE and DLL resources.
This is mission critical, would appreciate a response.

**Comment by fafalone** [comment]
Is this an actual string table? Looks like you're just treating it as binary data. If that's the case for now it seems to work if you just use a different resource type that doesn't conflict with one that has special handling... I tested it just as a "DATA" folder under Resources and that worked.

**Comment by TBDev111** [comment]
I am storing a large comma delimited string of numbers.   It is in the STRING resources section.  It works/loads fine in IDE, errors in compiled DLL.

**Comment by TBDev111** [comment]
I have managed to store the string in a large (650k) constant instead, so no longer mission-critical.

Thank you.

**Comment by SanbiVN** [comment]
@WaynePhillipsEA @fafalone @jpbro 

I encountered the following error:
```

-2147467259 Unspecified error.

```
From version 873 tb Beta to the present
When the program runs, a ```LoadResData``` call has resulted in the above error.

I am currently using version 872 tb Beta to build the application.

**Comment by WaynePhillipsEA** [comment]
@SanbiVN is that in a standard EXE tB project? If so, I can't reproduce it.

**Comment by WaynePhillipsEA** [comment]
Back to the OP, this problem only occurs if the resource folder is called "STRING".   We use that folder name for special JSON string tables, see Add menu > "Add Resource: String Table" for an example.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 940.  If the STRING resource folder does not contain .json files, the folder will now be treated as a regular named folder rather than a resource string table at build time.

**Comment by SanbiVN** [comment]
@WaynePhillipsEA 
I named the folder ```JS``` 
I downloaded the tb 940 Beta version, but I still encountered this error even after building it as a standard exe file.

<img width="600" height="400" alt="Image" src="https://github.com/user-attachments/assets/daae6412-c2e2-45cd-8256-93c86c1794c1" />

I've attached another project.

[OfficeAddinUpdater.zip](https://github.com/user-attachments/files/24256499/OfficeAddinUpdater.zip)


Thank you very much for your help.

**Comment by WaynePhillipsEA** [comment]
@SanbiVN Where is the call to LoadResData?  I cannot see it in your provided twinproj

**Comment by SanbiVN** [comment]
@WaynePhillipsEA
What I mean is that the project is still experiencing the same error.

**Comment by WaynePhillipsEA** [comment]
If it's not calling LoadResData, then it needs to be opened as a separate issue, as it is unrelated to this.

Also there are no text resource files in the file you provided, so I have no idea what I'm supposed to be looking at.

**Comment by SanbiVN** [comment]
@WaynePhillipsEA 
I don't know where the error is coming from; I only received the error message shown in this thread.

I've attached the built exe file.

[OfficeAddinUpdater_win32.zip](https://github.com/user-attachments/files/24256606/OfficeAddinUpdater_win32.zip)

**Comment by WaynePhillipsEA** [comment]
Please open a new issue.  This issue is for a bug involving LoadResData.

**Comment by SanbiVN** [comment]
@WaynePhillipsEA 

I'm very sorry, I changed the `COM Initialization` setting from multi-threaded to single-threaded, and the error disappeared.

Thank you very much for your support.

<img width="761" height="186" alt="Image" src="https://github.com/user-attachments/assets/553c0fa5-a590-41c6-b998-e967f00ac086" />
