### ISSUE TITLE
The editor could not be opened due to an unexpected error

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#483]
**Describe the bug**
Dodgy Code R Us are at it again!!

![EditorCouldNotBeOpened](https://user-images.githubusercontent.com/81257042/138727068-a3ec119c-251f-4f79-b236-24c72066af1c.jpg)

Clicking on try again or switching module and back clears the error but then shortly afterward the editor starts complaining that it cannot save.

**To Reproduce**
1. open the workspace of the attached project

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7411739/VBALib.zip)

**Expected behavior**
No errors when opening a project

**Desktop (please complete the following information):**
 - OS: [ Windows 11]
 - twinBASIC compiler version [v0.11.562]

**Comment by FullValueRider** [comment]
I'm not sure if this is relevant but I'm also occasionally seeing the following
![TwinBasicSaveAsError](https://user-images.githubusercontent.com/81257042/140096623-ba851978-9367-4488-925b-7d3829fbb55f.jpg)
If I press OK I get the message back 'Please enter a path that exists'

**Comment by FullValueRider** [comment]
I hope this helps.  I'm getting this error after some minor renaming in the  HelloWorld Project to prepare for Advent of Code 2021.  All that has changed is that the project has been set to 64 bit and the filename, project name and module renamed.

[AdventOfCode2021.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7621615/AdventOfCode2021.zip)

**Comment by WaynePhillipsEA** [comment]
This is now fixed in v0.13.68.   The message may appear briefly when you open the project, but it should fix itself now.

**Comment by FullValueRider** [comment]
Hi.  Unfortunately the problem appears to be only partially fixed.  If I was previously working with a split screen (i.e. two modules open for editing) then the pane that was being actively edited when I closed VSCode comes up as code, but the other pane still shows the 'unexpected error' message.

**Comment by WaynePhillipsEA** [comment]
Yes, the fix would only apply to the main active editor.

Once the tabs API gets added to VS Code, I should be able to offer a better fix for it. 
 https://github.com/microsoft/vscode/issues/133532

I'll reopen this so that we can look at it again once that VS code feature gets added.

**Comment by WaynePhillipsEA** [comment]
As this was a VS code specific issue, and it looks increasingly unlikely that we'll return to use VS Code in the near future, it's time to close this one. Thanks.
